name: venv-bookmarks
dependencies:
- python=3.10
- pip
- pip:
  - flask
  - flake8
  - black
  - pytest==7.2.0
  - flask-sqlalchemy
  - Flask-Migrate
  - python-dotenv
  - validators
  - flask-jwt-extended
  - flasgger